# Generated by Django 4.1.3 on 2023-01-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
